settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('ukrposhta_example.urls', 'ukrposhta_example'), namespace='ukrposhta_example')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ukrposhta_example/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', archive, name='archive'),
    path('letter/search', search_results, name='search_results'),
    path('letter/add/', letter_add, name='letter_add'),
    path('letter/<slug:slug>/details/', letter_details, name='letter_details'),
    path('letter/<slug:slug>/update/', UpdateLetterInfo.as_view(), name='letter_update'),
    path('recipient/add/', recipient_add, name='recipient_add'),
    path('recipients/list/', recipient_list, name='recipient_list'),
    path('sender/add/', sender_add, name='sender_add'),
    path('senders/list/', sender_list, name='sender_list'),
]

ukrposhta_example/models.py
from django.db import models
from django.template.defaultfilters import slugify

from django.urls import reverse


class RecipientModel(models.Model):
    STREET = [
        ('mkl', 'Мікльоша'),
        ('str', 'Стрийська'),
        ('sok', 'Сокільницька'),
    ]

    street = models.CharField(choices=STREET, max_length=3, default='str')

    BUILD = [
        ('', ''),
        ('3', '3'),
        ('5', '5'),
        ('7', '7'),
        ('9', '9'),
        ('11', '11'),
        ('13', '13'),
        ('15', '15'),
        ('17', '17'),
        ('20', '20'),
        ('23', '23'),
        ('25', '25'),
        ('27', '27'),
        ('73', '73'),
        ('75', '75'),
        ('77', '77'),
        ('79', '79'),
        ('81', '81'),
        ('85', '85'),
        ('87', '87'),
        ('89', '89'),
        ('91', '91'),
        ('93', '93'),
        ('99', '99'),
        ('101', '101'),
        ('103', '103'),
        ('105', '105'),
        ('107', '107'),
        ('111', '111'),
        ('113', '113'),
        ('115', '115'),
        ('117', '117'),
        ('123', '123'),
        ('127', '127'),
        ('129', '129'),
        ('133', '133'),
        ('260', '260'),
        ('262', '262'),
        ('264', '264'),
        ('266', '266'),
        ('268', '268'),
        ('270', '270'),
        ('272', '272'),
        ('274', '274'),
        ('276', '276'),
        ('278', '278'),
        ('280', '280'),
        ('282', '282'),
        ('284', '284'),
        ('286', '286'),
        ('288', '288'),
        ('290', '290'),
        ('292', '292'),
        ('294', '294'),
        ('296', '296'),
        ('298', '298'),
        ('300', '300'),
        ('302', '302'),
        ('304', '304'),
        ('306', '306'),
        ('308', '308'),
        ('310', '310'),
        ('312', '312'),
        ('314', '314'),
        ('316', '316'),
        ('318', '318'),
        ('320', '320'),
        ('322', '322'),
        ('324', '324'),
        ('326', '326'),
        ('328', '328'),
        ('330', '330'),
    ]

    build = models.CharField(choices=BUILD, max_length=3, default='')

    BUILD_LETTER = [
        ('', ''),
        ('A', 'А'),
        ('B', 'Б'),
        ('V', 'В'),
        ('G1', 'Г'),
        ('D', 'Д'),
        ('E1', 'Є'),
        ('E2', 'Е'),
        ('G2', 'Ж'),
    ]

    build_letter = models.CharField(choices=BUILD_LETTER, max_length=2, default='', blank=True)
    flat = models.CharField(max_length=4, blank=True)

    def get_absolute_url(self):
        return f'/{self.id}'

    def __str__(self):
        return f'{self.build}{self.build_letter}/{self.flat} {self.street}'

    class Meta:
        ordering = ['build']
        verbose_name = 'recipient'
        verbose_name_plural = 'Recipient'


class RecipientNameModel(models.Model):
    name = models.CharField(max_length=50)
    parent = models.ForeignKey(RecipientModel, related_name='subscriber_name',
                                db_index=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'subscriber name'
        verbose_name_plural = 'Subscriber names'


class SenderModel(models.Model):
    name = models.CharField(max_length=150, blank=True, unique=True,
                            error_messages={
                                'unique': 'Відправника вже було збережено раніше',
                            })

    # def validate_unique(self, exclude=None):
    #     super(SenderModel, self).validate_unique(exclude=exclude)

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.name)
    #     super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'sender'
        verbose_name_plural = 'Senders'


class LettersArchiveModel(models.Model):
    track_number = models.CharField(max_length=13, unique=True)
    slug = models.SlugField(max_length=13, unique=True, blank=True)
    date_of_storage_starting = models.DateField(auto_now=False, null=True, blank=True)
    repeat_delivery = models.BooleanField(default=False, blank=True, null=True)
    # repeat_delivery = models.ForeignKey('RepeatDelivery',
    #                                     related_name='letters_repeat_delivery',
    #                                     db_index=True,
    #                                     on_delete=models.PROTECT,
    #                                     blank=True,
    #                                     null=True)
    recipient_address = models.ForeignKey(RecipientModel,
                                          related_name='recipient_letter',
                                          db_index=True,
                                          on_delete=models.PROTECT)
    # recipient_name = models.CharField(max_length=45, blank=True)
    sender_data = models.ForeignKey(SenderModel,
                                    related_name='sender_letter',
                                    db_index=True,
                                    on_delete=models.CASCADE)
    is_court = models.BooleanField(default=False, blank=True)
    is_court_subpoena = models.BooleanField(default=False, blank=True)
    is_police = models.BooleanField(default=False, blank=True)
    is_police_fine = models.BooleanField(default=False, blank=True)
    is_letter_issued = models.BooleanField(default=False, blank=True)
    is_returned = models.BooleanField(default=False, blank=True)
    # letter_image = models.ImageField(upload_to='letters/letter_image/',
    #                                  default='letters/letter_image/default.png',
    #                                  blank=True,
    #                                  null=True)
    letter_image = models.CharField(max_length=100, unique=True)
    comments = models.TextField(blank=True)

    # def image_filename(self, filename):
    #     fname, dot, extension = filename.rpartition('.')
    #     slug = slugify(self.track_number)
    #     return '%s.%s' % (slug, extension)

    def get_absolute_url(self):
        return f'/{self.slug}'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.track_number)
        super(LettersArchiveModel, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.track_number} | Дата початку зберігання:  {self.date_of_storage_starting}. Cуд: {self.is_court} / Поліція: {self.is_police}. Видано: {self.is_letter_issued} / Повернуто: {self.is_returned}'

    class Meta:
        ordering = ['-id']
        verbose_name = 'лист на збереженні'
        verbose_name_plural = 'Листи на збереженні'


# class RepeatDelivery(models.Model):
#     letters = models.ForeignKey(LettersArchiveModel, db_index=True, on_delete=models.PROTECT)
#     date_of_storage_starting = models.DateField(auto_now=False, null=True, blank=True)
#     is_repeat = models.BooleanField(default=False)
#
#     def _str_(self):
#         return f'{self.is_repeat}: {self.date_of_storage_starting}'
#
#     class Meta:
#         verbose_name = 'repeat letter'
#         verbose_name_plural = 'Repeat letters'

ukrposhta_example/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import UpdateView

from .models import RecipientModel, LettersArchiveModel, SenderModel
from .forms import SearchForm, AddLetterForm, AddLetterModelForm, SenderNameFormSet, \
    AddSenderForm, AddRecipientModelForm, AddRecipientFormSet, AddRecipientForm


def recipient_add(request, recipient_id=None):
    # recipient = get_object_or_404(RecipientModel, id=recipient_id)

    if request.method == 'POST':
        recipient_form = AddRecipientForm(request.POST)
        if recipient_form.is_valid():
            build = recipient_form.cleaned_data['build']
            build_letter = recipient_form.cleaned_data['build_letter']
            flat = recipient_form.cleaned_data['flat']

            if RecipientModel.objects.filter(build=build).exists() and \
                    RecipientModel.objects.filter(build_letter=build_letter).exists() and \
                    RecipientModel.objects.filter(flat=flat).exists():
                messages.warning(request, 'Такого отримувача вже було збережено раніше')
            else:
                RecipientModel.objects.create(**recipient_form.cleaned_data)
    else:
        recipient_form = AddRecipientForm()

    # recipient_formset = SenderNameFormSet(request.POST)
    # if recipient_formset.is_valid():
    #     recipient_formset.save()
    #     messages.info(request, 'Отримувача було збережено')
    #     return HttpResponseRedirect(reverse('ukrposhta_example:letter_add'))
    # else:
    #     recipient_formset = SenderNameFormSet()

    context = {
        'title': 'Додати отримувача',
        # 'recipient_formset': recipient_formset,
        'recipient_form': recipient_form,
    }

    return render(request, 'ukrposhta_example/recipient_add.html', context=context)


def recipient_list(request):
    recipients = RecipientModel.objects.all()
    recipients_paginator = Paginator(recipients, 20)
    recipients_number = request.GET.get('page')
    recipients_numbers = recipients_paginator.get_page(recipients_number)

    context = {
        'title': 'Список отримувачів',
        'recipients_numbers': recipients_numbers,
    }

    return render(request, 'ukrposhta_example/recipient_list.html', context=context)


def sender_add(request):
    last_sender = SenderModel.objects.last()

    if request.method == 'POST':
        form = AddSenderForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            if SenderModel.objects.filter(name=name).exists():
                messages.warning(request, 'Відправника вже було додано раніше')
            else:
                SenderModel.objects.create(**form.cleaned_data)
                messages.info(request, 'Відправника було збережено')
                return HttpResponseRedirect(reverse('ukrposhta_example:letter_add'))
    else:
        form = AddSenderForm()

    context = {
        'title': 'Додати відправника',
        'last_sender': last_sender,
        'form': form,
    }

    return render(request, 'ukrposhta_example/sender_add.html', context=context)


def sender_list(request):
    sender = SenderModel.objects.all()
    sender_paginator = Paginator(sender, 20)
    sender_number = request.GET.get('page')
    sender_numbers = sender_paginator.get_page(sender_number)

    context = {
        'title': 'Додати відправника',
        'sender_numbers': sender_numbers,
    }

    return render(request, 'ukrposhta_example/sender_list.html', context=context)


def search_results(request):
    if request.method == 'GET':
        search_form = SearchForm(request.GET)
        if search_form.is_valid():
            query = search_form.cleaned_data['query']
            letter = LettersArchiveModel.objects.filter(
                Q(track_number__icontains=query) |
                Q(date_of_storage_starting__icontains=query)
            )

            context = {
                'query': query,
                'letter': letter,
            }

        return render(request, 'ukrposhta_example/search/search_results.html', context=context)


def archive(request):
    letters = LettersArchiveModel.objects.all()
    subscriber = RecipientModel.objects.all()

    context = {
        'title': 'Всі листи у Базі Даних',
        'letters': letters,
        'subscriber': subscriber,
    }

    return render(request, 'ukrposhta_example/archive.html', context=context)


def letter_add(request):
    letters = RecipientModel.objects.all()[:1]

    if request.method == 'POST':
        form = AddLetterForm(request.POST)
        if form.is_valid():
            date_of_storage_starting = form.cleaned_data['date_of_storage_starting']
            track_number = form.cleaned_data['track_number']
            recipient_address = form.cleaned_data['recipient_address']
            repeat_delivery = form.cleaned_data['repeat_delivery']
            is_court = form.cleaned_data['is_court']
            is_court_subpoena = form.cleaned_data['is_court_subpoena']
            is_police_fine = form.cleaned_data['is_police_fine']
            if LettersArchiveModel.objects.filter(track_number=track_number).exists():
                messages.warning(request, 'Лист із таким номером відстеження вже було додано раніше')
            else:
                LettersArchiveModel.objects.create(**form.cleaned_data)
                messages.success(request, f'Лист додано. №{track_number} |'
                                          f' Дата початку збереження: {date_of_storage_starting}.'
                                          f' Отримувач: {recipient_address}/'
                                          f' | Повторне: {repeat_delivery}/'
                                          f' Суд: {is_court}/'
                                          f'Повістка: {is_court_subpoena}, '
                                          f'Штраф: {is_police_fine},'
                                 )
                return HttpResponseRedirect(reverse('ukrposhta_example:letter_add'))
    else:
        form = AddLetterForm()

    context = {
        'title': 'Postman | Новий лист',
        'letters': letters,
        'last_letter': LettersArchiveModel.objects.last(),
        'form': form,
    }

    return render(request, 'ukrposhta_example/letter_add.html', context=context)


def letter_details(request, slug=None):
    letter_number = LettersArchiveModel.objects.get(slug=slug)
    letter_details = LettersArchiveModel.objects.filter(slug=slug)

    context = {
        'title': 'Деталі листа',
        'letter_number': letter_number,
        'letter_details': letter_details,
    }

    return render(request, 'ukrposhta_example/details.html', context=context)


class UpdateLetterInfo(SuccessMessageMixin, UpdateView):
    model = LettersArchiveModel
    template_name = 'ukrposhta_example/update_info.html'
    form_class = AddLetterModelForm
    success_message = 'Дані листа оновлено'

ukrposhta_example/templates/ukrposhta_example/letter_add.html
{% extends 'ukrposhta_example/_base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="row mt-4">
                    <div class="col-xl-2 col-lg-2 col-sm-12">
                        <form action="" method="post">
                            {% csrf_token %}

                        </form>
                    </div>
                    <div class="col-xl-2 xol-lg-2"></div>
                    <div class="col-xl-2 col-lg-2 col-sm-6 col-12">
                        <a href="{% url 'ukrposhta_example:recipient_add' %}"
                           class="btn button-blue right-angle w-100 mobile-text">Додати
                            отримувача</a>
                    </div>
                    <div class="col-xl-2 col-lg-2 col-sm-6 col-12">
                        <a href="{% url 'ukrposhta_example:sender_add' %}"
                           class="btn button-blue right-angle w-100 mobile-text">Додати
                            відправника</a>
                    </div>
                </div>
                <form action="" method="post" class="mobile-mt-2">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xl-2 col-lg-2 col-sm-6 col-12">{{ form.date_of_storage_starting }}</div>
                        <div class="col-xl-2 col-lg-2 col-sm-6 col-12">{{ form.track_number }}</div>
                        <div class="col-xl-2 col-lg-2 col-sm-6 col-12 mobile-mt-2">{{ form.recipient_address }}</div>
                        <div class="col-xl-6 col-lg-6 col-sm-6 col-12 mobile-mt-2">{{ form.sender_data }}</div>
                    </div>
                    <div class="row mt-4 mb-4">
                        <div class="col-xl-3 col-lg-3 col-sm-12 col-12 mt-1 text-center">{{ form.letter_image }}</div>
                        <div class="col-xl-4 col-lg-4 col-sm-12 col-12 border d-flex flex-row table-head mobile-mt-2">
                            <div class="row text-center">
                                <div class="col-xl-3 col-lg-3 col-sm-6 col-12 mx-auto mobile-text">
                                    Повторне: {{ form.repeat_delivery }}</div>
                                <div class="col-xl-3 col-lg-3 col-sm-6 col-12 mobile-text">
                                    Суд: {{ form.is_court }}</div>
                                <div class="col-xl-3 col-lg-3 col-sm-6 col-12 mx-auto mobile-text">
                                    Повістка: {{ form.is_court_subpoena }}</div>
                                <div class="col-xl-3 col-lg-3 col-sm-6 col-12 mobile-text">
                                    Штраф: {{ form.is_police_fine }}</div>
                            </div>
                        </div>
                        <div class="col-xl-5 col-lg-5 col-sm-12 col-12 mobile-mt-2">{{ form.comments }}</div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-4">
                            <button type="submit" class="btn button-light right-angle w-100 mobile-text mobile-mt-2">
                                Додати
                                лист
                            </button>
                        </div>
                    </div>
                </form>
                <table class="table mt-5">
                    <tbody>
                    {% for letter in letters %}
                        {% for item in letter.subscriber_letter.all %}
                            {% for name in letter.subscriber_name.all %}
                                <tr>
                                    <td>
                                        {% if item.letter_image is not None %}
                                            <img src="{% static 'images/default.png' %}" alt="item.track_number"
                                                 width="80">
                                        {% else %}
                                            <img src="{{ item.letter_image }}" alt="{{ item.track_number }}">
                                        {% endif %}
                                    </td>
                                    <th scope="row"><a href="" class="text-secondary">{{ item.track_number }}</a></th>
                                    <td>
                                        <a href="" class="text-secondary">
                                            {{ item.recipient_address }}
                                        </a>
                                        {{ name.name }}
                                    </td>
                                    <td>{{ item.sender_data }}</td>
                                    <td>
                                        <table class="table table-bordered">
                                            <tbody>
                                            <tr class="text-center">
                                                <td>
                                                    {% if letter.repeat_delivery %}
                                                        <span class="text-success-custom">Повторне</span>
                                                    {% else %}
                                                        <span class="text-secondary-light">
                                                        Повторне</span>
                                                    {% endif %}</td>
                                                <td>
                                                    {% if letter.is_court %}
                                                        <span class="text-success-custom">Суд</span>
                                                    {% else %}
                                                        <span class="text-secondary-light">
                                                        Суд</span>
                                                    {% endif %}</td>
                                                <td>
                                                    {% if letter.is_court_subpoena %}
                                                        <span class="text-success-custom">
                                                    Повістка
                                                </span>
                                                    {% else %}
                                                        <span class="text-secondary-light">
                                                        Повістка</span>
                                                    {% endif %}</td>
                                                <td>
                                                    {% if letter.is_police_fine %}
                                                        <span class="text-success-custom">
                                                        Штраф</span>
                                                    {% else %}
                                                        <span class="text-secondary-light">
                                                        Штраф</span>
                                                    {% endif %}</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endfor %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

ukrposhta_example/templates/ukrposhta_example/recipient_list.html
{% extends 'ukrposhta_example/_base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            {% for recipient in recipients_numbers %}
                <div class="col-xl-4 col-lg-6 col-sm-12 col-12">
                    <div class="card mt-3">
                        <div class="card-body row">
                            <div class="col-6 mobile-text">
                                {{ recipient.get_street_display }} {{ recipient.build }}
                                {% if recipient.build_letter %}
                                    {{ recipient.get_build_letter_display }}
                                {% endif %}
                                /{{ recipient.flat }}
                            </div>
                            <div class="col-6 d-flex justify-content-end">
                                <a href=""
                                   class="btn button-success mobile-text right-angle mx-auto">Листи</a>
                                <a href="" class="btn button-light mobile-text right-angle">Редагувати</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="row justify-content-center">
                <div class="col-4 d-flex">
                    <!-- pagination-->
                    <nav class="mt-1 mx-auto"
                         aria-label="Page navigation example">
                        <ul class="pagination">
                            <li class="page-item">
                                {% if recipients_numbers.has_previous %}
                                    <a class="page-link"
                                       href="?page={{ recipients_numbers.previous_page.number }}"
                                       aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                {% endif %}
                            </li>
                            {% for page in recipients_numbers.paginator.page_range %}
                                {% if page > recipients_numbers.number|add:-10 and page < recipients_numbers.number|add:10 %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page }}">{{ page }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            {% if recipients_numbers.has_next %}
                                <li class="page-item">
                                    <a class="page-link"
                                       href="?page={{ recipients_numbers.paginator.num_pages }}"
                                       aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                            <li class="page-item">
                            </li>
                        </ul>
                    </nav>
                    <!-- /pagination-->
                </div>
            </div>
        </div>
    </div>

{% endblock %}

ukrposhta_example/templates/ukrposhta_example/sender_list.html
{% extends 'ukrposhta_example/_base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            {% for sender in sender_numbers %}
                <div class="col-xl-4 col-lg-6 col-sm-12 col-12">
                    <div class="card mt-3">
                        <div class="card-body row">
                            <div class="col-6 mobile-text">
                                {{ sender.get_street_display }} {{ sender.build }}
                                {% if sender.build_letter %}
                                    {{ sender.get_build_letter_display }}
                                {% endif %}
                                /{{ sender.flat }}
                            </div>
                            <div class="col-6 d-flex justify-content-end">
                                <a href=""
                                   class="btn button-success mobile-text right-angle mx-auto">Листи</a>
                                <a href="" class="btn button-light mobile-text right-angle">Редагувати</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="row justify-content-center">
            <div class="col-4 d-flex">
                <!-- pagination-->
                <nav class="mt-1 mx-auto"
                     aria-label="Page navigation example">
                    <ul class="pagination">
                        <li class="page-item">
                            {% if sender_numbers.has_previous %}
                                <a class="page-link"
                                   href="?page={{ sender_numbers.previous_page.number }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            {% endif %}
                        </li>
                        {% for page in sender_numbers.paginator.page_range %}
                            {% if page > sender_numbers.number|add:-10 and page < sender_numbers.number|add:10 %}
                                <li class="page-item"><a class="page-link"
                                                         href="?page={{ page }}">{{ page }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if sender_numbers.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="?page={{ sender_numbers.paginator.num_pages }}"
                                   aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                        <li class="page-item">
                        </li>
                    </ul>
                </nav>
                <!-- /pagination-->
            </div>
        </div>
    </div>

{% endblock %}

ukrposhta_example/templates/ukrposhta_example/update_info.html
{% extends 'ukrposhta_example/_base.html' %}
{% load static %}

{% block content %}
    <div class="row mt-4">
        <div class="col-md-2">
            <form action="" method="post">
                {% csrf_token %}

            </form>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-2">
            <a href="{% url 'ukrposhta_example:recipient_add' %}" class="btn button-blue right-angle w-100">Додати отримувача</a>
        </div>
        <div class="col-md-2">
            <a href="{% url 'ukrposhta_example:sender_add' %}" class="btn button-blue right-angle w-100">Додати відправника</a>
        </div>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-2">{{ form.date_of_storage_starting }}</div>
            <div class="col-md-2">{{ form.track_number }}</div>
            <div class="col-md-2">{{ form.recipient_address }}</div>
            <div class="col-md-6">{{ form.sender_data }}</div>
        </div>
        <div class="row mt-4 mb-4">
            <div class="col-md-3 mt-1">{{ form.letter_image }}</div>
            <div class="col-md-4 border d-flex flex-row p-2 table-head">
                <div class="mx-auto">Повторне: {{ form.repeat_delivery }}</div>
                <div>Суд: {{ form.is_court }}</div>
                <div class="mx-auto">Повістка: {{ form.is_court_subpoena }}</div>
                <div>Штраф: {{ form.is_police_fine }}</div>
            </div>
            <div class="col-md-5">{{ form.comments }}</div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-4">
                <button type="submit" class="btn button-light right-angle w-100">Оновити дані</button>
            </div>
        </div>
    </form>
{% endblock %}